/// Model representing a verified B2B wholesale buyer.
class Buyer {
  final int id;
  final String name;
  final String company;
  final String? email;
  final String? phone;
  final String location;
  final String category;
  final String? description;

  Buyer({
    required this.id,
    required this.name,
    required this.company,
    this.email,
    this.phone,
    required this.location,
    required this.category,
    this.description,
  });

  factory Buyer.fromJson(Map<String, dynamic> json) {
    return Buyer(
      id: json['id'] as int,
      name: json['name'] as String? ?? 'Buyer',
      company: json['company'] as String? ?? 'Wholesale Buyer',
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      location: json['location'] as String? ?? 'India',
      category: json['category'] as String? ?? 'General',
      description: json['description'] as String?,
    );
  }
}

/// Model for buyer match results generated by the backend matching engine.
class BuyerMatch {
  final Buyer buyer;
  final int score;
  final String matchReason;

  BuyerMatch({
    required this.buyer,
    required this.score,
    required this.matchReason,
  });

  factory BuyerMatch.fromJson(Map<String, dynamic> json) {
    return BuyerMatch(
      buyer: Buyer.fromJson(json['buyer'] as Map<String, dynamic>),
      score: json['match_score'] as int? ?? json['score'] as int? ?? 80,
      matchReason: json['match_reason'] as String? ?? 'Matches product category',
    );
  }
}
